// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import AdvancedController from "controllers/advanced_controller"
application.register("advanced", AdvancedController)

import AvailabilityController from "controllers/availability_controller"
application.register("availability", AvailabilityController)

import BentoMasonryController from "controllers/bento-masonry_controller"
application.register("bento-masonry", BentoMasonryController)

import BookCoversController from "controllers/book_covers_controller"
application.register("book-covers", BookCoversController)

import BookmarkGuardController from "controllers/bookmark_guard_controller"
application.register("bookmark-guard", BookmarkGuardController)

import CitationCopyController from "controllers/citation_copy_controller"
application.register("citation-copy", CitationCopyController)

import ExplanationController from "controllers/explanation_controller"
application.register("explanation", ExplanationController)

import FinesController from "controllers/fines_controller"
application.register("fines", FinesController)

import HoldsController from "controllers/holds_controller"
application.register("holds", HoldsController)

import IndexController from "controllers/index_controller"
application.register("index", IndexController)

import LibGuidesController from "controllers/lib-guides_controller"
application.register("lib-guides", LibGuidesController)

import LoansController from "controllers/loans_controller"
application.register("loans", LoansController)

import PrimoController from "controllers/primo_controller"
application.register("primo", PrimoController)

import QueryListController from "controllers/query_list_controller"
application.register("query-list", QueryListController)

import RequestFormController from "controllers/request_form_controller"
application.register("request-form", RequestFormController)

import ShowController from "controllers/show_controller"
application.register("show", ShowController)
