// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AdvancedController from "./advanced_controller"
application.register("advanced", AdvancedController)

import ArticleIframeController from "./article_iframe_controller"
application.register("article-iframe", ArticleIframeController)

import AvailabilityController from "./availability_controller"
application.register("availability", AvailabilityController)

import BookCoversController from "./book_covers_controller"
application.register("book-covers", BookCoversController)

import ExplanationController from "./explanation_controller"
application.register("explanation", ExplanationController)

import FinesController from "./fines_controller"
application.register("fines", FinesController)

import HoldsController from "./holds_controller"
application.register("holds", HoldsController)

import IndexController from "./index_controller"
application.register("index", IndexController)

import LibGuidesController from "./lib-guides_controller"
application.register("lib-guides", LibGuidesController)

import LoansController from "./loans_controller"
application.register("loans", LoansController)

import PrimoController from "./primo_controller"
application.register("primo", PrimoController)

import QueryListController from "./query_list_controller"
application.register("query-list", QueryListController)

import RequestFormController from "./request_form_controller"
application.register("request-form", RequestFormController)

import ShowController from "./show_controller"
application.register("show", ShowController)
