version: "3.3"

services:
  solr:
    image: solr:9.8.1
    container_name: solr
    environment:
      SOLR_OPTS: "-Dsolr.config.lib.enabled=true"
    command:
      - bash
      - "-c"
      - |
        precreate-core blacklight /opt/solr/configs/tul_cob-catalog-solr && \
        precreate-core az-database /opt/solr/configs/tul_cob-az-solr && \
        precreate-core web-content /opt/solr/configs/tul_cob-web-solr && \
        solr-foreground
    ports:
      - "8983:8983"
    healthcheck:
      test: ["CMD","curl","-sf","http://localhost:8983/solr"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: .docker/ci-app/Dockerfile.ci
    working_dir: /app
    depends_on:
      - solr
    entrypoint:
      - sh
      - -c
      - |
        echo "⏳ waiting for solr…" \
        && until curl -sSf http://localhost:8983/solr > /dev/null; do sleep 1; done \
        && bundle exec rails ci
    environment:
      SOLRCLOUD_HOST: solr
      BUNDLE_PATH: /app/vendor/bundle
      DO_INGEST: ""
      LC_ALL: C.UTF-8
      SETTINGS__solr__host: solr
      SETTINGS__solr__username: catalog
      SETTINGS__solr__password: catalog
      SOLR_AZ_URL: http://localhost:8983/solr/tul_cob-az
      SOLR_URL: http://localhost:8983/solr/blacklight
      SOLR_WEB_CONTENT_URL: http://localhost:8983/solr/tul_cob-web
    ports:
      - "3000:3000"
