# = jetty_path key
# each environment can have a jetty_path with absolute or relative
# (to app root) path to a jetty/solr install. This is used
# by the rake tasks that start up solr automatically for testing
# and by rake solr:marc:index.
#
# jetty_path is not used by a running Blacklight application
# at all. In general you do NOT need to deploy solr in Jetty, you can deploy it
# however you want.
# jetty_path is only required for rake tasks that need to know
# how to start up solr, generally for automated testing.

development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core-dev" %>
  az_url: <%= ENV['SOLR_AZ_URL'] || "http://127.0.0.1:8983/solr/az-database" %>
  web_content_url: <%= ENV['SOLR_WEB_CONTENT_URL'] || "http://127.0.0.1:8983/solr/web-content" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8985}/solr/blacklight-core-test" %>
  az_url: <%= ENV['SOLR_AZ_URL'] || "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8985}/solr/az-database" %>
  web_content_url: <%= ENV['SOLR_WEB_CONTENT_URL'] || "http://127.0.0.1:8983/solr/web-content-test" %>
production:
  adapter: solr
  az_url: <%= ENV['SOLR_AZ_URL'] || "http://127.0.0.1:8983/solr/az-database" %>
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>
  web_content_url: <%= ENV['SOLR_WEB_CONTENT_URL'] || "http://127.0.0.1:8983/solr/web-content" %>
