---
api_key: 'foobar'
test:
  backend: test
exceptions:
  ignore:
    - "Alma::BibRequest::ItemAlreadyExists"
    - !ruby/regexp "an /No items can fulfill the submitted request/"
    - "ActiveRecord::RecordNotUnique"
