---
api_key: 'foobar'
test:
  backend: test
exceptions:
  ignore:
    - "Alma::BibRequest::ItemAlreadyExists"
    - "ActiveRecord::RecordNotUnique"
    - "Dalli::RingError"
    - "ActiveRecord::ConnectionNotEstablished"
