default: &default
  secret: <%= ENV["QUIK_PAY_SECRET"] || "MyQuikPaySecret" %>
  redirect_url: <%= ENV["QUIK_PAY_REDIRECT_URL"] || "http://localhost:3000/users/quik_pay_callback" %>

development:
    <<: *default

test:
    <<: *default

production:
    <<: *default
