

default: &default
  account_sid:  <%= ENV['TWILIO_ACCOUNT_SID']  || "TWILIO_ACCOUNT_SID" %>
  auth_token:   <%= ENV['TWILIO_AUTH_TOKEN']   || "TWILIO_AUTH_TOKEN" %>
  phone_number: <%= ENV['TWILIO_PHONE_NUMBER'] || "TWILIO_PHONE_NUMBER" %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
