# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path("../../lib", __FILE__)
require "simplecov"
require "alma"
require "webmock/rspec"
require "vcr"
require "database_cleaner"
require "capybara/rspec"

WebMock.disable_net_connect!(allow_localhost: true)

SPEC_ROOT = File.dirname __FILE__

SimpleCov.start "rails" do
  # Code from other repositories
  add_filter "/lib/alma_rb/"
  add_filter "/lib/alma-blacklight/"
  add_filter "/app/models/marc_indexer.rb"
  add_filter "/app/views/"
  add_filter "/app/channels/"
end
# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|

  config.before(:each) do

    # JUst so we don't send our request when testing controllers
    stub_request(:get, /.*almaws\/v1\/bibs\/.*/).to_return(status: 200, body: JSON.dump({}))
    stub_request(:post, /.*almaws\/v1\/bibs\/.*\/request-options?.*/).to_return(status: 200)
    stub_request(:post, /.*almaws\/v1\/bibs\/.*\/requests?.*/).to_return(status: 200)

    stub_request(:get, /.*\.exlibrisgroup\.com\/almaws\/v1\/bibs\/.*\/holdings\/.*\/items/).
        to_return(status: 200,
        body: File.open(SPEC_ROOT + "/fixtures/alma_data/bib_items_ambler_only.json"))

    stub_request(:get, /.*\.exlibrisgroup\.com\/almaws\/v1\/bibs\/same_campus\/holdings\/.*\/items/).
        to_return(status: 200,
        body: File.open(SPEC_ROOT + "/fixtures/alma_data/presser_and_paley.json"))

    stub_request(:get, /.*\.exlibrisgroup\.com\/almaws\/v1\/bibs\/ambler_presser\/holdings\/.*\/items/).
        to_return(status: 200,
        body: File.open(SPEC_ROOT + "/fixtures/alma_data/ambler_presser.json"))

    stub_request(:get, /.*\.exlibrisgroup\.com\/almaws\/v1\/bibs\/kardon_paley\/holdings\/.*\/items/).
        to_return(status: 200,
        body: File.open(SPEC_ROOT + "/fixtures/alma_data/kardon_paley.json"))

    stub_request(:get, /.*\.exlibrisgroup\.com\/almaws\/v1\/bibs\/only_paley_reserves\/holdings\/.*\/items/).
        to_return(status: 200,
        body: File.open(SPEC_ROOT + "/fixtures/requests/only_paley_reserves.json"))

    stub_request(:get, /.*\.exlibrisgroup\.com\/almaws\/v1\/bibs\/paley_reserves_and_remote_storage\/holdings\/.*\/items/).
        to_return(status: 200,
        body: File.open(SPEC_ROOT + "/fixtures/requests/paley_reserves_and_remote_storage.json"))

    stub_request(:get, /.*\.exlibrisgroup\.com\/almaws\/v1\/bibs\/no_reserve_or_reference\/holdings\/.*\/items/).
        to_return(status: 200,
        body: File.open(SPEC_ROOT + "/fixtures/requests/no_reserve_or_reference.json"))

    stub_request(:get, /.*\.exlibrisgroup\.com\/almaws\/v1\/bibs\/both_reserve\/holdings\/.*\/items/).
        to_return(status: 200,
        body: File.open(SPEC_ROOT + "/fixtures/requests/both_reserve.json"))

    stub_request(:get, /.*\.exlibrisgroup\.com\/almaws\/v1\/bibs\/desc_with_no_libraries\/holdings\/.*\/items/).
        to_return(status: 200,
        body: File.open(SPEC_ROOT + "/fixtures/requests/desc_with_no_libraries.json"))

    stub_request(:get, /.*\.exlibrisgroup\.com\/almaws\/v1\/bibs\/desc_with_multiple_libraries\/holdings\/.*\/items/).
        to_return(status: 200,
        body: File.open(SPEC_ROOT + "/fixtures/requests/desc_with_multiple_libraries.json"))

    stub_request(:get, /.*\.exlibrisgroup\.com\/almaws\/v1\/bibs/).
        with(query: hash_including(expand: "p_avail,e_avail,d_avail", mms_id: "1,2")).
        to_return(status: 200,
                  body: File.open(SPEC_ROOT + "/fixtures/availability_response.xml").read,
                  headers: { "content-type" => ["application/xml;charset=UTF-8"] })

  end
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # The settings below are suggested to provide a good initial experience
  # with RSpec, but feel free to customize to your heart's content.

  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  config.filter_run_excluding relevance: true unless ENV["RELEVANCE"]

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  #   - http://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/
  #   - http://www.teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/
  #   - http://rspec.info/blog/2014/05/notable-changes-in-rspec-3/#zero-monkey-patching-mode
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  #if config.files_to_run.one?
  # Use the documentation formatter for detailed output,
  # unless a formatter has already been configured
  # (e.g. via a command-line flag).
  #config.default_formatter = 'doc'
  #end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed

  config.add_setting :bento_expected_fields,
    default: [ :title, :authors, :publisher, :link ]

  # So we can test logged in users.
  require "warden"
  config.include Warden::Test::Helpers

end

VCR.configure do |config|
  config.allow_http_connections_when_no_cassette = true
  config.cassette_library_dir = "spec/fixtures/vcr_cassettes"
  config.hook_into :webmock
  config.default_cassette_options = {
    match_requests_on: [:method]
  }
end

if ENV["RELEVANCE"] && ENV["RELEVANCE"] != "test_only"
  RSpec.configure do |config|
    config.before(:suite) do
      require "rake"
      Rails.application.load_tasks
      Rake::Task["fortytu:solr:load_fixtures"].invoke("#{SPEC_ROOT}/relevance/fixtures/*.xml")
    end
  end
end

require "rspec/expectations"
RSpec::Matchers.define :include_docs do |more_relevant_docs|
  match do |actual|
    ids = ids(actual)
    # Find index of relevant docs in array of actual ids
    # if any of the docs are not in the actual index (which returns nil), throw an exception
    more_relevant_index_points = more_relevant_docs.map { |d| ids.index(d) }
    raise ArgumentError.new("At least one of the more relevant docs was not in the results set") unless more_relevant_index_points.none?(&:nil?)

    #grab the largest index
    last_more_relevant_index = more_relevant_index_points.compact.max

    # if we used the before chain method
    if less_relevant_docs

      # Find index of the less relevant docs in array of actual ids and grab the smallest index
      # if none of the docs are in the actual index (which returns nil), set to 1 more than
      # thu number of returned results
      first_less_relevant_index = (
        less_relevant_docs.map { |d| ids.index(d) }.compact.min ||
        (actual.dig("response", "pages", "total_count") || 100) + 1)

      # The last more relevant doc should have a smaller index
      # than the firs less relevant doc
      last_more_relevant_index < first_less_relevant_index

    #if we used the within_the_first chain method
    elsif within_index
      last_more_relevant_index < within_index
    end
  end

  chain :before, :less_relevant_docs

  chain :within_the_first, :within_index

  failure_message do |actual|
    if less_relevant_docs
      "expected that #{more_relevant_docs} would be appear before #{less_relevant_docs} in #{ids(actual)}"
    elsif within_index
      "expected that #{more_relevant_docs} would appear in the first #{within_index} docs"
    end

  end

  def ids(actual)
    (actual.dig("response", "docs") || {}).map { |doc| doc.fetch("id") }.compact
  end
end
