// Entry point for the build script in your package.json
import "@stimulus/polyfills"
import "@hotwired/turbo-rails"
import "whatwg-fetch"
import "typeahead.js"
import "./src/jquery"
import * as bootstrap from "bootstrap"
import "selectize"
import "./controllers"

import Blacklight from "./blacklight/core"
import "./src/blacklight_alma_lib"
import "./src/application"
import "./src/summary_previews"
import "./src/blacklight_overrides"
import "./src/availability"
import "./src/article_iframe"
import "./src/libwizard_tutorial"

import "./blacklight/autocomplete"
import "./blacklight/bookmark_toggle"
import "./blacklight/button_focus"
import "./blacklight/checkbox_submit"
import "./blacklight/core"
import "./blacklight/facet_load"
import "./blacklight/modal"
import "./blacklight/search_context"