FROM ruby:2.7.2-alpine3.11
RUN apk --update add nodejs yarn git build-base bash  mysql-dev sqlite-dev tzdata shared-mime-info
RUN mkdir /app
WORKDIR /app
COPY . .
RUN gem install bundler:2.2.17
RUN ls config/*example | xargs -I{} echo {} |  cut -d '.' -f-2 | xargs -I{} cp {}.example {}
CMD ["bash"]
