FROM ruby:3.1-alpine
RUN apk --update add nodejs yarn git build-base bash mysql-dev sqlite-dev tzdata shared-mime-info libssl-dev
RUN mkdir /app
WORKDIR /app
ENV RAILS_ENV='test'
COPY . .
RUN ls config/*example | xargs -I{} echo {} |  cut -d '.' -f-2 | xargs -I{} cp {}.example {}
CMD ["bash"]
