FROM ruby:3.4-alpine
RUN apk add -U --no-cache --virtual build-dependencies \
      build-base \
      bash \
      chromium \
      chromium-chromedriver \
      git \
      yaml \
      yaml-dev \
      libxslt-dev \
      libffi-dev \
      postgresql16-dev \
      nodejs \
      sqlite-dev \
      yarn tzdata shared-mime-info
RUN mkdir /app
WORKDIR /app
ENV RAILS_ENV='test'
COPY . .
RUN ls config/*example | xargs -I{} echo {} |  cut -d '.' -f-2 | xargs -I{} cp {}.example {}
CMD ["bash"]
